version: 1.0
app:
  instances:
    min: 1
    max: 2
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
  variables:
    - name: discoveryEndpoint
      value: https://adrian-001100.verify.ibm.com/oidc/endpoint/default/.well-known/openid-configuration
    - name: clientId
      value: de48d6f2-d8ae-4b74-ab02-3c18670984de
  version: "dfaf24e5-32e8-49e5-9afe-94f5cc516eb4"
  java: 17
